name: gallos_app_new
description: "Aplicación profesional para gestión de gallos de pelea - GallosPro"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Estado y navegación
  provider: ^6.1.1
  go_router: ^12.1.3
  
  # HTTP y conectividad
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  
  # UI y multimedia
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  video_player: ^2.8.1
  
  # Almacenamiento local (cache mínimo)
  shared_preferences: ^2.2.2
  
  # Utilidades
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Iconos
  cupertino_icons: ^1.0.2
  
  # Crypto para encriptación
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/data/mock/
    - assets/images/
    - assets/images/gallos/
    - assets/images/logo/
